name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prettier:
    name: Prettier formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    
    - name: Install asdf
      uses: asdf-vm/actions/setup@v1.0.0
    
    - name: Install asdf plugins
      run: 'scripts/asdf-add-plugins.sh'
    
    - name: Install asdf tools versions
      run: 'scripts/asdf-install.sh'

    - name: Check Prettier formatting 
      run: 'scripts/check-prettier.sh'
      
  check-rendered-up-to-date:
    name: Rendered 'docs/' up to date
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    
    - name: Install asdf
      uses: asdf-vm/actions/setup@v1.0.0
    
    - name: Install asdf plugins
      run: 'scripts/asdf-add-plugins.sh'
    
    - name: Install asdf tools versions
      run: 'scripts/asdf-install.sh'

    - name: Check that 'docs' folder is up to date
      run: 'scripts/check-rendered-site-up-to-date.sh'
